# Generated by Django 4.1.7 on 2023-07-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
