# Generated by Django 4.1.7 on 2023-07-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_profile_elo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='elo',
            field=models.IntegerField(default=1000),
        ),
    ]
