# Generated by Django 4.1.7 on 2023-07-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_profile_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
