# Generated by Django 4.1.7 on 2023-07-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_profile_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='modified_at',
        ),
    ]
