# Generated by Django 4.1.7 on 2023-07-19 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0009_remove_profile_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='in_queue',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='QueuePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(related_name='queuers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
