# Generated by Django 4.1.7 on 2023-07-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='message',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(max_length=60),
        ),
    ]
