# Generated by Django 4.1.7 on 2023-07-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_feedback_message_alter_feedback_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ava',
            field=models.ImageField(default='compete copy 2/mainapp/static/images/userlogodefault.jpg', upload_to='avatars'),
        ),
    ]
