# Generated by Django 4.1.7 on 2023-08-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
