# Generated by Django 4.1.7 on 2023-08-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_profile_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=models.ImageField(default='/static/images/userlogodefault.jpg', upload_to='backgrounds'),
        ),
    ]
