# Generated by Django 4.1.7 on 2023-07-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word_game',
            name='solved',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='word_game_guess',
        ),
    ]
