# Generated by Django 4.1.7 on 2023-07-13 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_game_current_player_game_waiter_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='current_player',
        ),
        migrations.RemoveField(
            model_name='game',
            name='waiter_player',
        ),
        migrations.AddField(
            model_name='round',
            name='current_player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='current_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='round',
            name='waiter_player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='waiter_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
