# Generated by Django 4.1.7 on 2023-07-13 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_remove_game_current_player_remove_game_waiter_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='current_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='round',
            name='waiter_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiter_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
