# Generated by Django 4.1.7 on 2023-07-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_game_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
    ]
