# Generated by Django 4.1.7 on 2023-07-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='item',
        ),
    ]
